name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:

  tests:
    name: Test code
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go:
          - ^1.18
          - ^1.19
          - ^1
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 200

    - name: Run tests
      run: |
        make
        make test
